### ISSUE TITLE
In what relation does this repository stand compared to the main lazygit repoitory?

### ISSUE THREAD

**Issue by PlexSheep** [kaisenlinux/lazygit#1]
I couldn't find a notice of this repository being a fork of the main repo https://github.com/jesseduffield/lazygit , what is its purpose?

**Comment by kaisenlinux** [comment]
It's the same code of the original repository.

It's a source of the Debian packaging for Kaisen Linux. We have applied few patchs of the original code in the debian/patches directory.

**Comment by PlexSheep** [comment]
Sounds good. I was just wondering. It might be a good idea to clarify this in the README.

**Comment by kaisenlinux** [comment]
No,
We will have to create a patch to commit this modification in the README.md file.
We don't want to maintain a patch only for that.
